// <auto-generated />
namespace assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class namechangeCountry_IdinCountry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(namechangeCountry_IdinCountry));
        
        string IMigrationMetadata.Id
        {
            get { return "201708011103028_namechangeCountry_IdinCountry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
